#!/usr/bin/env bash

set -euo pipefail

export ESPHOME_DASHBOARD_USE_PING=true

libretiny_args=(
  dashboard
)

if [[ -n ${DASHBOARD_USER} && -n ${DASHBOARD_PASSWORD} ]]; then
  libretiny_args+=(
    --username "${DASHBOARD_USER}"
    --password "${DASHBOARD_PASSWORD}"
  )
fi

if [[ -f /etc/pki/libretiny/server.crt && -f /etc/pki/libretiny/private/server.key ]]; then
  printf "Enable SSL for Tornado web server\n"
  patch --quiet --strip=1 --directory=/usr/local/libretiny-esphome < /usr/local/src/tornado-enable-ssl.patch
fi

cd /usr/local/libretiny-esphome || exit
python3 -m esphome "${libretiny_args[@]}" /etc/libretiny
