---

name: "Build and push container image"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

env:
  IMAGE_NAME: libretiny
  IMAGE_REGISTRY: quay.io
  REGISTRY_USER: ${{ github.repository_owner }}

jobs:
  build:
    name: "Build and push container image for ${{ github.event.repository.name }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: "Build container image ${{ github.event.repository.name }}"
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          containerfiles: |
            ./Containerfile

      - name: "Push container image ${{ github.event.repository.name }} to quay.io"
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}/${{ env.REGISTRY_USER }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Print URL for ${{ github.event.repository.name }} container image"
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
